### PR TITLE
Moving documentation to single-spa.js.org

### PR DESCRIPTION
**Pull request by internettrans**
See related https://github.com/CanopyTax/single-spa.js.org/pull/76

We are trying to consolidate all documentation into single-spa.js.org, for easier use and maintenance of single-spa.

### CODE REVIEW

**Comment by internettrans** [comment]
Also, could you take a look at #5, so that I can help out with the maintenance of this project?

**Comment by internettrans** [comment]
any update on this?

**Comment by internettrans** [comment]
any update?

**Comment by ariesjia** [comment]
sorry to replay late,  I didn't notice the notification in the mail. 
merged

**Pull request merged**
